export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <h1>Example from https://nextjs.org/learn/react-foundations/server-and-client-components</h1>
      <body>{children}</body>
    </html>
  )
}
